include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false

analyzer:
  exclude:
    - '**.g.dart'
#    - 'lib/firebase_options.dart'
  errors:
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: ignore