name: naviquezon
description: "A new Flutter project that can be use to create itinerary list 
for user, add and edit establishment for owner, and get the report for tourist admin"
publish_to: 'none'
version: 1.0.16+1

environment:
  sdk: ^3.5.3

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  chat_bubbles: ^1.7.0
  chewie: ^1.9.0
  chopper: ^8.0.3
  country_list: ^0.0.5
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  excel: ^4.0.6
  file_picker: ^8.1.7
  firebase_core: ^3.10.0
  firebase_database: ^11.3.0
  firebase_storage: ^12.4.0
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.4.0
  flutter_keyboard_visibility: ^6.0.0
  fluttertoast: ^8.2.10
  fpdart: ^1.1.1
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^14.6.3
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  month_picker_dialog: ^6.0.3
  permission_handler: ^11.3.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.5
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.14
  chopper_generator: ^8.0.3
  flutter_gen_runner: ^5.8.0
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/icons/amenities/
    - assets/images/backgrounds/
    - assets/images/headers/

# Generate assets.gen.dart and fonts.gen.dart from assets folder
# Run the command in terminal
# dart run build_runner build --delete-conflicting-outputs
flutter_gen:
  output: lib/src/core/themes/
  integrations:
    flutter_svg: true
    lottie: true


# Update the app icon
# Run the command in terminal
# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icons/ic-app.png"